/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Michał Solarek (https://sketchfab.com/misiek13)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-little-japanese-town-street-200fc33b8a2b4da98e71590feeb255a8
Title: Stylized Little Japanese Town Street
*/

import React, { useRef , useEffect} from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame , useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'
import townScene from "../assets/townScene.glb"

const Town = (props) =>{
  const { nodes, materials } = useGLTF(townScene)
  return (
    <a.group {...props} dispose={null}>
      <a.group rotation={[-Math.PI / 2, 0, 0]}>
        <a.group rotation={[Math.PI / 2, 0, 0]}>
          <a.group position={[-20.22, 305.439, -19.554]} rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
            <a.group position={[-96.786, -52.619, -120.32]}>
              <mesh
                geometry={nodes.defaultMaterial_3.geometry}
                material={materials['13___Default']}
              />
              <mesh
                geometry={nodes.defaultMaterial_4.geometry}
                material={materials['13___Default']}
              />
            </a.group>
            <mesh
              geometry={nodes.defaultMaterial.geometry}
              material={materials['08___Default']}
              position={[50.984, -213.906, -116.617]}
            />
            <mesh
              geometry={nodes.defaultMaterial_1.geometry}
              material={materials['09___Default']}
              position={[90.99, -81.507, -120.251]}
            />
            <mesh
              geometry={nodes.defaultMaterial_2.geometry}
              material={materials['19___Default']}
              position={[-70.374, 170.437, -120.251]}
            />
            <mesh
              geometry={nodes.defaultMaterial_5.geometry}
              material={materials['14___Default']}
              position={[89.515, 123.647, -120.251]}
            />
            <mesh
              geometry={nodes.defaultMaterial_6.geometry}
              material={materials['15___Default']}
              position={[81.404, 200.691, -120.251]}
            />
            <mesh
              geometry={nodes.defaultMaterial_7.geometry}
              material={materials['01___Default']}
              position={[91.323, 184.667, -124.505]}
            />
            <mesh
              geometry={nodes.defaultMaterial_8.geometry}
              material={materials['20___Default']}
              position={[-21.302, 15.657, -119.547]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.999}
            />
            <mesh
              geometry={nodes.defaultMaterial_9.geometry}
              material={materials['07___Default']}
              position={[-75.078, -189.472, -120.251]}
            />
          </a.group>
        </a.group>
      </a.group>
    </a.group>
  )
}


export default Town;